---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  roles:
    - docker