---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    mysql_container_name: mysql5
    mysql_database: mydb
    mysql_memory_limit: 1G
    mysql_config_mysqld:
      max_connections: 500
      skip_name_resolve: "true"    
    mysql_env:
      MYSQL_DATABASE: mydb
      MYSQL_USER: kakaoi
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: 127.0.0.1
  roles:
    - docker
    - mysql