---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    mysql_port: 3306
    mysql_root_password: change-me
    mysql_data_directory: /data
    default_container_image: mysql:8
    default_container_name: mysql8
  roles:
    - docker
    - mysql