---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
#    mysql_port: 3306
    mysql_root_password: change-me
    mysql_data_directory: /data
    mysql_memory_limit: 1G
    default_container_image: mysql:5.7.18
    default_container_name: mysql5
  roles:
    - docker
    - mysql