---
- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
#   command: "{{ default_container_command }}"
#    ports:
#      - "{{ mysql_port }}:3306"
    network_mode: host
    volumes:
      - "{{ mysql_data_directory }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    restart: true
    restart_policy: unless-stopped
    state: started
